/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches, matchPrecache } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst, CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope;

// Offline HTML fallback
// NOTE: This HTML is minified and inlined to avoid VitePWA build issues.
// For maintenance, edit the formatted version in swUtils.ts and then minify it here.
const OFFLINE_HTML = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Offline - Budget Wise</title><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;display:flex;justify-content:center;align-items:center;min-height:100vh;margin:0;background:#f5f5f5}.container{text-align:center;padding:20px;max-width:400px}h1{color:#333;margin-bottom:10px}p{color:#666;margin-bottom:20px}button{background:#007AFF;color:white;border:none;padding:12px 24px;border-radius:8px;font-size:16px;cursor:pointer}button:hover{background:#0056b3}</style></head><body><div class="container"><h1>You\'re Offline</h1><p>Please check your internet connection and try again.</p><button onclick="window.location.reload()">Retry</button></div></body></html>';

// Cache names for offline state management
const OFFLINE_STATE_CACHE = 'offline-state';
const OFFLINE_STATE_KEY = 'forceOffline';

// NOTE: Functions below are inlined from swUtils.ts
// VitePWA's injectManifest strategy cannot resolve cross-file ES module imports
// during service worker compilation, causing build failures.
// These functions are duplicated here to work around this limitation.
// swUtils.ts is retained for testing purposes.
//
// ⚠️ MAINTENANCE WARNING: If you modify these functions, you MUST also
// update the corresponding functions in swUtils.ts to maintain consistency.
// Both files contain identical implementations for the same functionality.

// Inlined from swUtils.ts: setOfflineState
async function setOfflineState(offline: boolean): Promise<void> {
    try {
        const cache = await caches.open(OFFLINE_STATE_CACHE);
        await cache.put(
            OFFLINE_STATE_KEY,
            new Response(JSON.stringify({ offline }), {
                headers: { 'Content-Type': 'application/json' },
            })
        );
    } catch (error) {
        console.error('[SW] Failed to save offline state:', error);
    }
}

// Inlined from swUtils.ts: loadOfflineState
async function loadOfflineState(): Promise<boolean> {
    try {
        const cache = await caches.open(OFFLINE_STATE_CACHE);
        const response = await cache.match(OFFLINE_STATE_KEY);
        if (response) {
            const data = await response.json();
            return data.offline;
        }
    } catch (error) {
        console.error('[SW] Failed to load offline state:', error);
    }
    return false;
}

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches from previous versions
cleanupOutdatedCaches();

// Logic to force offline mode via message
let forceOffline = false;

// Initialize offline state from cache
loadOfflineState().then((offline) => {
    forceOffline = offline;
    console.log('[SW] Offline mode initialized to:', forceOffline);
});

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SET_OFFLINE_MODE') {
        forceOffline = event.data.offline;
        setOfflineState(forceOffline);
        console.log('[SW] Offline mode set to:', forceOffline);
    }
});

// Navigation route - serve from cache, fallback to network, then offline page
const navigationHandler = new NetworkFirst({
    cacheName: 'navigations',
    plugins: [
        new CacheableResponsePlugin({
            statuses: [0, 200],
        }),
    ],
});

registerRoute(
    new NavigationRoute(async (params) => {
        if (forceOffline) {
            // In forced offline mode, serve the shell immediately from cache
            const cached = await matchPrecache('/index.html');
            if (cached) return cached;
            // If cache miss, return minimal offline HTML page
            return new Response(OFFLINE_HTML, { headers: { 'Content-Type': 'text/html' } });
        }

        try {
            // Try network first (includes caching the response if successful)
            const response = await navigationHandler.handle(params);
            if (response) return response;
        } catch (error) {
            // Network request failed - proceed to fallback below
        }

        // Fallback to the precached index.html for ANY navigation error/failure
        // This ensures client-side routes (like /onboarding) still load the main shell
        const cached = await matchPrecache('/index.html');
        if (cached) return cached;
        // If cache miss, return minimal offline HTML page
        return new Response(OFFLINE_HTML, { headers: { 'Content-Type': 'text/html' } });
    })
);

// Cache Google Fonts Stylesheets
registerRoute(
    ({ url }) => url.origin === 'https://fonts.googleapis.com',
    new StaleWhileRevalidate({
        cacheName: 'google-fonts-stylesheets',
    })
);

// Cache Google Fonts Webfonts with CacheFirst and expiration (original behavior)
registerRoute(
    ({ url }) => url.origin === 'https://fonts.gstatic.com',
    new CacheFirst({
        cacheName: 'google-fonts-webfonts',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 Year
                maxEntries: 30,
            }),
        ],
    })
);

// Cache CSS and JS files with Stale-while-revalidate
registerRoute(
    ({ request }) => request.destination === 'style' || request.destination === 'script' || request.destination === 'worker',
    new StaleWhileRevalidate({
        cacheName: 'assets',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
    })
);

// Cache Images with expiration (original behavior)
registerRoute(
    ({ request }) => request.destination === 'image',
    new StaleWhileRevalidate({
        cacheName: 'images',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
    })
);

self.addEventListener('install', (event) => {
    event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});

