import { COMMAND_TYPES } from '../../commands/types.js';
import type { MigrationIntegrationFixture } from './types.js';

// Rows reconciliation creates for the imported recurring item: its batch of
// 12 occurrences, counted from the legacy start date.
const GENERATED_RECURRING_OCCURRENCES = 12;

export const edgeCaseFixture: MigrationIntegrationFixture = {
  credentials: {
    email: 'migration-edge@example.com',
    password: 'Secret123!',
    token: 'token-edge-case',
  },
  responses: {
    'POST /user/get-token': { token: 'token-edge-case' },
    'GET /api/accounts': [
      {
        id: 150,
        name: 'Edge Cases',
        acronym: 'EC',
        color: '#336699',
        deleted: false,
      },
    ],
    'GET /api/access': [
      {
        id: 2,
        role: 'owner',
        account: 150,
        user: { id: 12, email: 'migration-edge@example.com' },
      },
    ],
    'GET /api/balance?account_id=150': [
      {
        id: 501,
        name: 'Valid Grocery',
        balanceType: 'BT_EXPENSE',
        date: '2026-03-01T08:00:00.000Z',
        amount: 20,
        deleted: false,
        account: 150,
        category: 1,
        saving_goal: null,
        recuring: null,
        user: 12,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
      {
        id: 502,
        name: 'Deleted Transaction',
        balanceType: 'BT_EXPENSE',
        date: '2026-03-02T08:00:00.000Z',
        amount: 10,
        deleted: true,
        account: 150,
        category: 1,
        saving_goal: null,
        recuring: null,
        user: 12,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
      {
        id: 503,
        name: 'Transfer To Savings',
        balanceType: 'BT_EXPENSE',
        date: '2026-03-03T08:00:00.000Z',
        amount: 80,
        deleted: false,
        account: 150,
        category: 1,
        saving_goal: null,
        recuring: null,
        user: 12,
        target_account: 999,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: true,
      },
      {
        id: 504,
        name: 'Missing Category',
        balanceType: 'BT_EXPENSE',
        date: '2026-03-04T08:00:00.000Z',
        amount: 40,
        deleted: false,
        account: 150,
        category: null,
        saving_goal: null,
        recuring: null,
        user: 12,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
      {
        id: 505,
        name: 'Unknown Category',
        balanceType: 'BT_EXPENSE',
        date: '2026-03-05T08:00:00.000Z',
        amount: 15,
        deleted: false,
        account: 150,
        category: 999,
        saving_goal: null,
        recuring: null,
        user: 12,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
      {
        id: 506,
        name: 'Board Games',
        balanceType: 'BT_EXPENSE',
        date: '2026-03-06T08:00:00.000Z',
        amount: 55,
        deleted: false,
        account: 150,
        category: 4,
        saving_goal: null,
        recuring: null,
        user: 12,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
    ],
    'GET /api/category?account_id=150': [
      {
        id: 1,
        name: 'Essen',
        icon: 'kategorie_ausgaben_3',
        balanceType: 'BT_EXPENSE',
        active: true,
        is_deletable: true,
        limits: 120,
        limitsDate: '2026-03-31',
        deleted: false,
        account: 150,
        default: null,
      },
      {
        id: 2,
        name: 'Obsolete Category',
        icon: 'kategorie_ausgaben_1',
        balanceType: 'BT_EXPENSE',
        active: true,
        is_deletable: true,
        limits: null,
        limitsDate: null,
        deleted: true,
        account: 150,
        default: null,
      },
      {
        id: 3,
        name: 'Inactive Category',
        icon: 'kategorie_ausgaben_1',
        balanceType: 'BT_EXPENSE',
        active: false,
        is_deletable: true,
        limits: null,
        limitsDate: null,
        deleted: false,
        account: 150,
        default: null,
      },
      {
        id: 4,
        name: 'Board Games',
        icon: 'kategorie_ausgaben_11',
        balanceType: 'BT_EXPENSE',
        active: true,
        is_deletable: true,
        limits: null,
        limitsDate: null,
        deleted: false,
        account: 150,
        default: null,
      },
    ],
    'GET /api/recuring?account_id=150': [
      {
        id: 601,
        name: 'Monthly Board Games Club',
        balanceType: 'BT_EXPENSE',
        startDate: '2026-03-01',
        endDate: null,
        nextRepeatingDate: null,
        amount: 15,
        repeating: 1,
        deleted: false,
        category: 4,
        account: 150,
      },
      {
        id: 602,
        name: 'Broken Interval',
        balanceType: 'BT_EXPENSE',
        startDate: '2026-03-01',
        endDate: null,
        nextRepeatingDate: null,
        amount: 99,
        repeating: 0,
        deleted: false,
        category: 4,
        account: 150,
      },
    ],
    'GET /api/saving-goal?category_id=1': [],
    'GET /api/saving-goal?category_id=2': [],
    'GET /api/saving-goal?category_id=3': [],
    'GET /api/saving-goal?category_id=4': [],
  },
  expected: {
    imported: {
      accounts: 1,
      transactions: 2,
      categories: 2,
      limits: 1,
      templates: 0,
      recurringItems: 1,
      savingsGoals: 0,
    },
    loggedCommandTypes: [
      COMMAND_TYPES.CREATE_ACCOUNT,
      COMMAND_TYPES.BULK_CREATE_CATEGORIES,
      COMMAND_TYPES.CREATE_CATEGORY, // Essen (is_deletable: true → user-created)
      COMMAND_TYPES.CREATE_CATEGORY, // Board Games (is_deletable: true → user-created)
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_LIMIT,
      COMMAND_TYPES.CREATE_RECURRING,
      ...Array.from({ length: GENERATED_RECURRING_OCCURRENCES }, () => COMMAND_TYPES.CREATE_TRANSACTION),
    ],
    generatedRecurringOccurrences: GENERATED_RECURRING_OCCURRENCES,
    warningsContains: [
      'Skipped transfer transaction',
      'has no category — skipped',
      'references unknown category 999',
      'invalid repeating interval',
    ],
  },
};
