import { COMMAND_TYPES } from '../../commands/types.js';
import type { MigrationIntegrationFixture } from './types.js';

// Rows reconciliation creates for the imported recurring item. Pet Insurance
// starts on 5 Jan, but its first booked occurrence is balance 205 on 5 Feb,
// which is reused: the batch of 12 counts from 5 Feb, so 11 are generated.
const GENERATED_RECURRING_OCCURRENCES = 11;

export const minimalAccountFixture: MigrationIntegrationFixture = {
  credentials: {
    email: 'migration-happy@example.com',
    password: 'Secret123!',
    token: 'token-happy-path',
  },
  responses: {
    'POST /user/get-token': { token: 'token-happy-path' },
    'GET /api/accounts': [
      {
        id: 96,
        name: 'Family Budget',
        acronym: 'FB',
        color: '#ff8840',
        deleted: false,
      },
    ],
    'GET /api/access': [
      {
        id: 1,
        role: 'owner',
        account: 96,
        user: { id: 9, email: 'migration-happy@example.com' },
      },
    ],
    'GET /api/balance?account_id=96': [
      {
        id: 201,
        name: 'Monthly Salary',
        balanceType: 'BT_INCOME',
        date: '2026-02-01T08:00:00.000Z',
        amount: 2000,
        deleted: false,
        account: 96,
        category: 102,
        saving_goal: 401,
        recuring: null,
        user: 9,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
      {
        id: 202,
        name: 'Grocery Run',
        balanceType: 'BT_EXPENSE',
        date: '2026-02-02T12:00:00.000Z',
        amount: 45.2,
        deleted: false,
        account: 96,
        category: 101,
        saving_goal: null,
        recuring: null,
        user: 9,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
      {
        id: 203,
        name: 'Vet Fund',
        balanceType: 'BT_EXPENSE',
        date: '2026-02-03T12:00:00.000Z',
        amount: 60,
        deleted: false,
        account: 96,
        category: 103,
        saving_goal: null,
        recuring: null,
        user: 9,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
      {
        id: 204,
        name: 'Side Gig',
        balanceType: 'BT_INCOME',
        date: '2026-02-04T18:00:00.000Z',
        amount: 150,
        deleted: false,
        account: 96,
        category: 102,
        saving_goal: null,
        recuring: null,
        user: 9,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
      {
        id: 205,
        name: 'Dog Food',
        balanceType: 'BT_EXPENSE',
        date: '2026-02-05T10:30:00.000Z',
        amount: 30,
        deleted: false,
        account: 96,
        category: 103,
        saving_goal: null,
        recuring: 301,
        user: 9,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
    ],
    'GET /api/category?account_id=96': [
      {
        id: 101,
        name: 'Essen',
        icon: 'kategorie_ausgaben_3',
        balanceType: 'BT_EXPENSE',
        active: true,
        is_deletable: true,
        limits: 300,
        limitsDate: '2026-02-28',
        deleted: false,
        account: 96,
        default: null,
      },
      {
        id: 102,
        name: 'Lohn',
        icon: 'kategorie_einnahmen_2',
        balanceType: 'BT_INCOME',
        active: true,
        is_deletable: false,
        limits: null,
        limitsDate: null,
        deleted: false,
        account: 96,
        default: null,
      },
      {
        id: 103,
        name: 'Pet Care',
        icon: 'kategorie_ausgaben_11',
        balanceType: 'BT_EXPENSE',
        active: true,
        is_deletable: true,
        limits: null,
        limitsDate: null,
        deleted: false,
        account: 96,
        default: null,
      },
    ],
    'GET /api/recuring?account_id=96': [
      {
        id: 301,
        name: 'Pet Insurance',
        balanceType: 'BT_EXPENSE',
        startDate: '2026-01-05',
        endDate: null,
        nextRepeatingDate: null,
        amount: 25,
        repeating: 1,
        deleted: false,
        category: 103,
        account: 96,
      },
    ],
    'GET /api/saving-goal?category_id=101': [],
    'GET /api/saving-goal?category_id=102': [],
    'GET /api/saving-goal?category_id=103': [
      {
        id: 401,
        name: 'Emergency Vet Buffer',
        created_at: '2026-01-10',
        dueDate: '2026-12-31',
        amount: 500,
        monthly_amount: 50,
        isopen: true,
        deleted: false,
        category: 103,
        account: 96,
      },
    ],
  },
  expected: {
    imported: {
      accounts: 1,
      transactions: 5,
      categories: 3,
      limits: 1,
      templates: 0,
      recurringItems: 1,
      savingsGoals: 1,
    },
    loggedCommandTypes: [
      COMMAND_TYPES.CREATE_ACCOUNT,
      COMMAND_TYPES.BULK_CREATE_CATEGORIES,
      COMMAND_TYPES.CREATE_CATEGORY, // Essen (is_deletable: true → user-created)
      COMMAND_TYPES.CREATE_CATEGORY, // Pet Care (is_deletable: true → user-created)
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_LIMIT,
      COMMAND_TYPES.CREATE_RECURRING,
      COMMAND_TYPES.CREATE_SAVINGS_GOAL,
      ...Array.from({ length: GENERATED_RECURRING_OCCURRENCES }, () => COMMAND_TYPES.CREATE_TRANSACTION),
    ],
    generatedRecurringOccurrences: GENERATED_RECURRING_OCCURRENCES,
    warningsContains: [],
  },
};
