import { COMMAND_TYPES } from '../../commands/types.js';
import type { MigrationIntegrationFixture } from './types.js';

// Rows reconciliation creates for the imported recurring item: its batch of
// 12 occurrences, counted from the legacy start date.
const GENERATED_RECURRING_OCCURRENCES = 12;

export const multiAccountFixture: MigrationIntegrationFixture = {
  credentials: {
    email: 'migration-multi@example.com',
    password: 'Secret123!',
    token: 'token-multi-account',
  },
  responses: {
    'POST /user/get-token': { token: 'token-multi-account' },
    'GET /api/accounts': [
      {
        id: 201,
        name: 'Personal Legacy',
        acronym: 'PE',
        color: '#ff8840',
        deleted: false,
      },
      {
        id: 202,
        name: 'Shared Flat',
        acronym: 'SF',
        color: '#4488cc',
        deleted: false,
      },
      {
        id: 203,
        name: 'Archived Legacy',
        acronym: 'AR',
        color: '#666666',
        deleted: true,
      },
    ],
    'GET /api/access': [
      {
        id: 11,
        role: 'owner',
        account: 201,
        user: { id: 20, email: 'migration-multi@example.com' },
      },
      {
        id: 12,
        role: 'member',
        account: 202,
        user: { id: 20, email: 'migration-multi@example.com' },
      },
      {
        id: 13,
        role: 'owner',
        account: 203,
        user: { id: 20, email: 'migration-multi@example.com' },
      },
    ],
    'GET /api/balance?account_id=201': [
      {
        id: 1001,
        name: 'Groceries',
        balanceType: 'BT_EXPENSE',
        date: '2026-04-01T08:00:00.000Z',
        amount: 90,
        deleted: false,
        account: 201,
        category: 901,
        saving_goal: null,
        recuring: null,
        user: 20,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
      {
        id: 1002,
        name: 'Dog Walking',
        balanceType: 'BT_INCOME',
        date: '2026-04-02T08:00:00.000Z',
        amount: 45,
        deleted: false,
        account: 201,
        category: 902,
        saving_goal: null,
        recuring: null,
        user: 20,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
    ],
    'GET /api/balance?account_id=202': [
      {
        id: 1003,
        name: 'Shared Salary',
        balanceType: 'BT_INCOME',
        date: '2026-04-03T08:00:00.000Z',
        amount: 2200,
        deleted: false,
        account: 202,
        category: 903,
        saving_goal: 1101,
        recuring: null,
        user: 20,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
      {
        id: 1004,
        name: 'Utilities',
        balanceType: 'BT_EXPENSE',
        date: '2026-04-04T08:00:00.000Z',
        amount: 140,
        deleted: false,
        account: 202,
        category: 904,
        saving_goal: null,
        recuring: 1201,
        user: 20,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
    ],
    'GET /api/balance?account_id=203': [
      {
        id: 1005,
        name: 'Archived Expense',
        balanceType: 'BT_EXPENSE',
        date: '2026-04-05T08:00:00.000Z',
        amount: 12,
        deleted: false,
        account: 203,
        category: 905,
        saving_goal: null,
        recuring: null,
        user: 20,
        target_account: null,
        sender_account: null,
        target_balance_id: null,
        sender_balance_id: null,
        is_transfer_balance: false,
      },
    ],
    'GET /api/category?account_id=201': [
      {
        id: 901,
        name: 'Essen',
        icon: 'kategorie_ausgaben_3',
        balanceType: 'BT_EXPENSE',
        active: true,
        is_deletable: true,
        limits: 200,
        limitsDate: '2026-04-30',
        deleted: false,
        account: 201,
        default: null,
      },
      {
        id: 902,
        name: 'Dog Walking',
        icon: 'kategorie_einnahmen_5',
        balanceType: 'BT_INCOME',
        active: true,
        is_deletable: true,
        limits: null,
        limitsDate: null,
        deleted: false,
        account: 201,
        default: null,
      },
    ],
    'GET /api/category?account_id=202': [
      {
        id: 903,
        name: 'Lohn',
        icon: 'kategorie_einnahmen_2',
        balanceType: 'BT_INCOME',
        active: true,
        is_deletable: false,
        limits: null,
        limitsDate: null,
        deleted: false,
        account: 202,
        default: null,
      },
      {
        id: 904,
        name: 'Utilities Plus',
        icon: 'kategorie_ausgaben_8',
        balanceType: 'BT_EXPENSE',
        active: true,
        is_deletable: true,
        limits: 150,
        limitsDate: '2026-04-30',
        deleted: false,
        account: 202,
        default: null,
      },
    ],
    'GET /api/category?account_id=203': [
      {
        id: 905,
        name: 'Bücher',
        icon: 'kategorie_ausgaben_5',
        balanceType: 'BT_EXPENSE',
        active: true,
        is_deletable: true,
        limits: null,
        limitsDate: null,
        deleted: false,
        account: 203,
        default: null,
      },
    ],
    'GET /api/recuring?account_id=201': [],
    'GET /api/recuring?account_id=202': [
      {
        id: 1201,
        name: 'Monthly Utilities',
        balanceType: 'BT_EXPENSE',
        startDate: '2026-04-01',
        endDate: null,
        nextRepeatingDate: null,
        amount: 140,
        repeating: 1,
        deleted: false,
        category: 904,
        account: 202,
      },
    ],
    'GET /api/recuring?account_id=203': [],
    'GET /api/saving-goal?category_id=901': [],
    'GET /api/saving-goal?category_id=902': [],
    'GET /api/saving-goal?category_id=903': [],
    'GET /api/saving-goal?category_id=904': [
      {
        id: 1101,
        name: 'Rainy Day Fund',
        created_at: '2026-04-01',
        dueDate: '2027-01-31',
        amount: 1200,
        monthly_amount: 100,
        isopen: true,
        deleted: false,
        category: 904,
        account: 202,
      },
    ],
    'GET /api/saving-goal?category_id=905': [],
  },
  expected: {
    imported: {
      accounts: 2,
      transactions: 4,
      categories: 4,
      limits: 2,
      templates: 0,
      recurringItems: 1,
      savingsGoals: 1,
    },
    loggedCommandTypes: [
      // Account 201 — Personal Legacy
      COMMAND_TYPES.CREATE_ACCOUNT,
      COMMAND_TYPES.BULK_CREATE_CATEGORIES,
      COMMAND_TYPES.CREATE_CATEGORY, // Essen (is_deletable: true → user-created)
      COMMAND_TYPES.CREATE_CATEGORY, // Dog Walking (is_deletable: true → user-created)
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_LIMIT,
      // Account 202 — Shared Flat
      COMMAND_TYPES.CREATE_ACCOUNT,
      COMMAND_TYPES.BULK_CREATE_CATEGORIES,
      COMMAND_TYPES.CREATE_CATEGORY, // Utilities Plus (is_deletable: true → user-created)
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_TRANSACTION,
      COMMAND_TYPES.CREATE_LIMIT,
      COMMAND_TYPES.CREATE_RECURRING,
      COMMAND_TYPES.CREATE_SAVINGS_GOAL,
      ...Array.from({ length: GENERATED_RECURRING_OCCURRENCES }, () => COMMAND_TYPES.CREATE_TRANSACTION),
    ],
    generatedRecurringOccurrences: GENERATED_RECURRING_OCCURRENCES,
    warningsContains: [],
  },
};
